services:
  nginx:
    image: nginx:1.25.0-alpine
    container_name: backup-mng-nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - ${APP_EXTERNAL_PORT}:80
    depends_on:
      - app

  app:
      build:
        context: .
        dockerfile: _docker/app/Dockerfile
        args:
          user: backup_mng
          uid: 1002
      container_name: backup-mng-app
      working_dir: /var/www
      volumes:
        - ./:/var/www
      depends_on:
        - db

  db:
    image: mariadb:10.11
    container_name: backup-mng-db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 3
    ports:
      - ${DB_EXTERNAL_PORT}:3306
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - backup_mng_db:/var/lib/mysql

volumes:
  backup_mng_db:
